<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.ftn.uns.ac.rs/xws/cbs/firma"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ws="http://www.example.com/webservice"
    
    xmlns:f="http://www.ftn.uns.ac.rs/xws/cbs/firma"
    xmlns:t="http://www.ftn.uns.ac.rs/xws/cbs/tipovi"
    xmlns:fkt="http://www.ftn.uns.ac.rs/xws/cbs/faktura">
    <!-- 3 iznad su naknadno dodati namespace-ovi -->
    <!-- importi -->
    <wsdl:types>
        <xs:schema xmlns="http://www.w3.org/2001/XMLSchema">
            <xs:import namespace="http://www.ftn.uns.ac.rs/xws/cbs/tipovi" schemaLocation="tipovi.xsd"/>
            <xs:import namespace="http://www.ftn.uns.ac.rs/xws/cbs/faktura" schemaLocation="faktura.xsd"/>
        </xs:schema>
    </wsdl:types>
    
    <!-- parametri metode -->
    <wsdl:message name="prometRequest">
        <wsdl:part name="kupljeno" element="fkt:faktura"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="prometResponse">
        <wsdl:part name="response" element="fkt:faktura"></wsdl:part>
    </wsdl:message>
    
    <!-- port -->
    <wsdl:portType name="Firma">
        <wsdl:operation name="promet">
            <wsdl:input message="f:prometRequest"></wsdl:input>
            <wsdl:output message="f:prometResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>

    <!-- binding -->
    <wsdl:binding name="FirmaBinding" type="f:Firma">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="promet">
            <soap:operation soapAction=""/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <!-- service -->
    <wsdl:service name="FirmaService">
        <wsdl:port name="Firma" binding="f:FirmaBinding">
            <soap:address location="http://localhost:8080/firma"/>
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>