//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.15 at 05:40:23 PM CET 
//


package rs.ac.uns.ftn.xws.cbs.mt102;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xws.cbs.mt102 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mt102_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/cbs/mt102", "mt102");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xws.cbs.mt102
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MT102 }
     * 
     */
    public MT102 createMT102() {
        return new MT102();
    }

    /**
     * Create an instance of {@link MT102PojedinacniNalog }
     * 
     */
    public MT102PojedinacniNalog createMT102PojedinacniNalog() {
        return new MT102PojedinacniNalog();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MT102 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/cbs/mt102", name = "mt102")
    public JAXBElement<MT102> createMt102(MT102 value) {
        return new JAXBElement<MT102>(_Mt102_QNAME, MT102 .class, null, value);
    }

}
